import type { NextPage } from 'next'
import Head from 'next/head'


const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>HOME | Templete</title>
        <meta name="description" content="Generated by create next app" />
        {/* <link rel="icon" href="/favicon.ico" /> */}
      </Head>

      <main>
        <h1>Olá mundo</h1>
        {/* <img src={bonequinhoComBolsas} alt="Boneco" />
      <Logo /> */}
      </main>
    </div>
  )
}

export default Home
